#app.yaml
runtime: python312
env: standard
instance_class: B2 

# Run gunicorn on app object in app.py
entrypoint: gunicorn -b :$PORT app:app

# Spin up 2 instances
manual_scaling:
  instances: 2

# Specify machine type
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  CLOUD_SQL_USERNAME: hood-amh52-user
  CLOUD_SQL_PASSWORD: password
  CLOUD_SQL_DATABASE_NAME: database-project
  CLOUD_SQL_CONNECTION_NAME: hood-amh52:us-central1:hood-amh52-instance
